### ISSUE TITLE
list card not showing anymore after HA update..

### ISSUE THREAD

**Issue by aaamoeder** [custom-cards/list-card#20]
there is no error, nothing.. just no card is shown without altering any of the config..

Could this be this issue ?
--> https://github.com/atomic7777/atomic_calendar/issues/63

**Comment by iantrich** [comment]
No, this card makes a copy of the config. I don't think that's the issue. But I'm also probably not going to "fix" it. I'll release a re-write at some point, just not sure when.

**Comment by aaamoeder** [comment]
It was a stupid error on my part ... 🤦‍♂ 
Just thought it was something bigger since the calendar card failed at the exact same time (that was due to the google.token)
Consider this closed 😄

**Comment by aaamoeder** [comment]
It was a stupid error on my part ... 🤦‍♂ 
Just thought it was something bigger since the calendar card failed at the exact same time (that was due to the google.token)
Consider this closed 😄

**Comment by iantrich** [comment]
oh good 👍

**Comment by cerebrate** [comment]
I have also been having atomic calendar fail after the update to 0.106.0, and as far as I can tell, it _is_ #63, since adding

```
config = JSON.parse(JSON.stringify(config));
```

to the top of your setConfig() method fixes it. Problem is, I think, that you're making a shallow copy of the config, which means you still can't write to this.config.entities even through this.config is writable.

(Anyway, adding that line in app.js and rerunning `rollup` to generate a new atomic_calendar.js is the workaround for anyone else having this particular issue.)
